### ISSUE TITLE
Setup heroku redirects

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/American-Lang220#18]
So we talked about setting up ingidio.com/manga , ingidio.com/videos, ingidio.com/games, ingidio.com/porn for the respective signup pages for the respective parties, so let's set this up. Create the pages for manga, videos, etc. on the main ingidio site, but have them do a redirect to the heroku site that actually hosts them

For instance, http://cold-frost-9554.heroku.com right now holds the manga page.

**Comment by SpinnakerSix** [comment]
okay this is done manually in American-Lit-400 by changed in the redirections function in the pages controller. I'm trying to make it programmatically possible. 

Ingidio.com/manga should now redirect to cold-frost-9554.heroku.com

**Comment by SpinnakerSix** [comment]
Redirection speed is also a pain in the ass right now. So slow that i thought my browser crashed. 

This can be fixed by pulling American-Lit-400 and pushing it up again onto heroku. You should see the Procfile which automatically starts the thin server in heroku which should increase rendering speed. InGidio.com is now running on this.

**Comment by SpinnakerSix** [comment]
this is now done programmatically at Ingidio/settings

check it out and add as many new redirects as you want.
